### ISSUE TITLE
Thanks and AV1 choices

### ISSUE THREAD

**Issue by fcore117** [yzu1103309/YouTube-Downloader#1]
Finally an YT-DLp GUI app that is C++ not some .net framework or Electron garbage. Please expand codec choices in future if you want. Thanks.

**Comment by yzu1103309** [comment]
@fcore117 Hi, apologies for the delayed response. I've been occupied with my academic subjects.

I'm delighted that you enjoy this application. It has been updated to version 3.0.0 (see [Release](https://github.com/yzu1103309/YouTube-Downloader/releases/tag/v3.0.0)), now featuring codec selection (AV1, VP9, H.264). However, please note that not every video offers the AV1 codec option. In such cases, it will fallback to using VP9.

If you have any further questions, please feel free to contact me at any time. Your recommendations for this application to others would be greatly appreciated. Thank you.

**Comment by fcore117** [comment]
> @fcore117 Hi, apologies for the delayed response. I've been occupied with my academic subjects.
> 
> I'm delighted that you enjoy this application. It has been updated to version 3.0.0 (see [Release](https://github.com/yzu1103309/YouTube-Downloader/releases/tag/v3.0.0)), now featuring codec selection (AV1, VP9, H.264). However, please note that not every video offers the AV1 codec option. In such cases, it will fallback to using VP9.
> 
> If you have any further questions, please feel free to contact me at any time. Your recommendations for this application to others would be greatly appreciated. Thank you.

Thanks.
